# Generated by Django 6.0.4 on 2026-04-15 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='层级名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('target_ratio', models.FloatField(default=0, verbose_name='目标比例(%)')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='颜色代码')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产层级',
                'verbose_name_plural': '资产层级',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', '周检视'), ('monthly', '月检视'), ('quarterly', '季度检视'), ('yearly', '年度检视')], max_length=20, verbose_name='检视类型')),
                ('completed_items', models.JSONField(default=list, verbose_name='已完成项')),
                ('total_items', models.IntegerField(default=0, verbose_name='总项数')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='完成时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '检视记录',
                'verbose_name_plural': '检视记录',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='键')),
                ('value', models.TextField(blank=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '设置',
                'verbose_name_plural': '设置',
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='快照日期')),
                ('total_value', models.FloatField(default=0, verbose_name='总资产(元)')),
                ('layer_values', models.JSONField(default=dict, verbose_name='各层级市值')),
                ('layer_ratios', models.JSONField(default=dict, verbose_name='各层级比例')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产快照',
                'verbose_name_plural': '资产快照',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='截图')),
                ('recognized_data', models.JSONField(blank=True, default=list, verbose_name='识别结果')),
                ('status', models.CharField(choices=[('pending', '待识别'), ('processing', '识别中'), ('recognized', '已识别'), ('confirmed', '已确认'), ('failed', '识别失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '截图上传',
                'verbose_name_plural': '截图上传',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='代码')),
                ('asset_type', models.CharField(choices=[('cash', '现金'), ('money_fund', '货币基金'), ('bank_product', '银行理财'), ('deposit', '存款/大额存单'), ('bond_fund', '债券基金'), ('convertible_bond', '可转债基金'), ('index_fund', '指数基金'), ('stock', '股票'), ('etf', 'ETF'), ('dividend_stock', '红利股'), ('gold', '黄金'), ('qdii', 'QDII基金'), ('hk_stock', '港股'), ('other', '其他')], default='other', max_length=30, verbose_name='资产类型')),
                ('quantity', models.FloatField(default=0, verbose_name='数量/份额')),
                ('cost_price', models.FloatField(blank=True, null=True, verbose_name='成本价/买入均价')),
                ('current_price', models.FloatField(blank=True, null=True, verbose_name='当前价/净值')),
                ('market_value', models.FloatField(default=0, verbose_name='市值(元)')),
                ('profit_loss', models.FloatField(default=0, verbose_name='盈亏(元)')),
                ('profit_loss_pct', models.FloatField(default=0, verbose_name='盈亏比例(%)')),
                ('source', models.CharField(choices=[('manual', '手动输入'), ('screenshot', '截图识别')], default='manual', max_length=20, verbose_name='数据来源')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.assetlayer', verbose_name='所属层级')),
            ],
            options={
                'verbose_name': '持仓',
                'verbose_name_plural': '持仓',
                'ordering': ['-market_value'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', '买入'), ('sell', '卖出'), ('dividend', '分红'), ('rebalance', '再平衡'), ('transfer', '转入'), ('withdraw', '转出')], max_length=20, verbose_name='操作类型')),
                ('asset_name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('quantity', models.FloatField(default=0, verbose_name='数量')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('amount', models.FloatField(default=0, verbose_name='金额(元)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='操作日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='assets.holding', verbose_name='关联持仓')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
