# Generated by Django 6.0.4 on 2026-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='platform',
            field=models.CharField(blank=True, help_text='如：招商银行、支付宝、天天基金、雪球等', max_length=100, verbose_name='来源平台'),
        ),
        migrations.AddField(
            model_name='upload',
            name='platform',
            field=models.CharField(blank=True, help_text='截图所属的 App/平台', max_length=100, verbose_name='来源平台'),
        ),
    ]
