# Generated by Django 6.0.4 on 2026-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_holding_platform_upload_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlayer',
            name='target_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='目标比例(%)'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='成本价/买入均价'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='当前价/净值'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='市值(元)'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='盈亏(元)'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='profit_loss_pct',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='盈亏比例(%)'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='数量/份额'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='总资产(元)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='金额(元)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='数量'),
        ),
    ]
