# Generated by Django 6.0.4 on 2026-04-15 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetlayer_target_ratio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-date', '-id'], 'verbose_name': '资产快照', 'verbose_name_plural': '资产快照'},
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='快照时间'),
        ),
    ]
