# Generated by Django 6.0.4 on 2026-04-17 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_snapshot_options_alter_snapshot_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评估时间')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='总资产(元)')),
                ('score', models.IntegerField(default=0, verbose_name='健康评分')),
                ('overall_health', models.CharField(max_length=50, verbose_name='整体健康度')),
                ('summary_data', models.JSONField(default=dict, verbose_name='总结数据')),
                ('holdings_data', models.JSONField(default=list, verbose_name='持仓评估')),
            ],
            options={
                'verbose_name': '评估报告',
                'verbose_name_plural': '评估报告',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
