# Generated by Django 6.0.4 on 2026-04-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_evaluationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='holdings_data',
            field=models.JSONField(blank=True, default=list, verbose_name='持仓明细'),
        ),
    ]
