# Generated by Django 6.0.4 on 2026-04-18 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_snapshot_holdings_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='assets.assetlayer', verbose_name='所属层级'),
        ),
    ]
