# Generated by Django 6.0.4 on 2026-04-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_holding_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='is_reserve',
            field=models.BooleanField(default=False, help_text='标记为应急储备/干火药，不参与常规再平衡部署', verbose_name='干火药储备'),
        ),
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(help_text='如：concentration_5pct, satellite_stop_loss_30, satellite_take_profit_50', max_length=50, verbose_name='预警类型')),
                ('action', models.CharField(choices=[('acknowledged', '已知悉'), ('acted', '已执行操作'), ('dismissed', '暂不处理')], max_length=20, verbose_name='处置方式')),
                ('notes', models.TextField(blank=True, verbose_name='处置备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='处置时间')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_actions', to='assets.holding', verbose_name='关联持仓')),
            ],
            options={
                'verbose_name': '预警处置',
                'verbose_name_plural': '预警处置',
                'ordering': ['-created_at'],
            },
        ),
    ]
