# Generated by Django 6.0.4 on 2026-04-18 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_holding_is_reserve_alertaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='market_value',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=18, verbose_name='市值(元)'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='快照时间'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='操作日期'),
        ),
    ]
