# Generated by Django 6.0.4 on 2026-04-18 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_holding_market_value_alter_snapshot_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='类型')),
                ('category', models.CharField(choices=[('salary', '工资'), ('bonus', '奖金'), ('freelance', '兼职/副业'), ('investment_income', '投资收益'), ('interest', '利息收入'), ('other_income', '其他收入'), ('rent', '房租/房贷'), ('food', '餐饮'), ('transport', '交通'), ('utilities', '水电物业'), ('shopping', '购物'), ('medical', '医疗'), ('education', '教育'), ('entertainment', '娱乐'), ('insurance', '保险'), ('other_expense', '其他支出')], max_length=30, verbose_name='分类')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额(元)')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='日期')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('is_recurring', models.BooleanField(default=False, help_text='标记为定期收支（如每月工资、房租）', verbose_name='定期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '现金流',
                'verbose_name_plural': '现金流',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform',
            field=models.CharField(blank=True, max_length=100, verbose_name='平台'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='realized_pnl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='卖出时的已实现盈亏', max_digits=18, null=True, verbose_name='已实现盈亏'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', '手动'), ('auto', '自动生成'), ('ocr', 'OCR识别')], default='manual', max_length=20, verbose_name='来源'),
        ),
    ]
