# Generated by Django 6.0.4 on 2026-04-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_cashflow_transaction_platform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFlow',
        ),
    ]
