# Generated by Django 6.0.4 on 2026-04-19 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_drop_cashflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评估时间')),
                ('asset_name', models.CharField(db_index=True, max_length=200, verbose_name='资产名称')),
                ('score', models.IntegerField(default=0, verbose_name='健康评分')),
                ('signal', models.CharField(max_length=20, verbose_name='操作信号')),
                ('signal_reason', models.CharField(max_length=500, verbose_name='信号理由')),
                ('risk_level', models.CharField(max_length=20, verbose_name='风险等级')),
                ('analysis_data', models.JSONField(default=dict, verbose_name='分析详情')),
                ('action_plan', models.TextField(blank=True, default='', verbose_name='操作建议')),
                ('risks', models.JSONField(default=list, verbose_name='风险点')),
                ('highlights', models.JSONField(default=list, verbose_name='亮点')),
            ],
            options={
                'verbose_name': '资产评估',
                'verbose_name_plural': '资产评估',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
