# Generated by Django 6.0.4 on 2026-05-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_assetevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='备份名称')),
                ('data', models.JSONField(verbose_name='备份数据')),
                ('is_auto', models.BooleanField(default=False, verbose_name='是否自动备份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统备份',
                'verbose_name_plural': '系统备份',
                'ordering': ['-created_at'],
            },
        ),
    ]
