# Generated by Django 6.0.4 on 2026-05-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_systembackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='profit_loss_pct',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='盈亏比例(%)'),
        ),
    ]
