# Generated by Django 6.0.4 on 2026-06-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_fix_profit_loss_pct_max_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
