# Generated by Django 6.0.4 on 2026-06-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_transaction_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='buy_thesis',
            field=models.TextField(blank=True, help_text='为什么买这只资产（护城河/现金流/估值等）。卖出时用于校验「投资逻辑是否破坏」', verbose_name='买入逻辑'),
        ),
        migrations.AddField(
            model_name='holding',
            name='industry',
            field=models.CharField(blank=True, db_index=True, help_text='如：白酒、银行、科技、医药、电力等。用于行业集中度分析与「个人财富—企业风险脱钩」检视', max_length=50, verbose_name='行业/板块'),
        ),
    ]
