# Generated by Django 6.0.4 on 2026-06-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_holding_buy_thesis_holding_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('', '自动(按类型)'), ('broad', '宽基指数'), ('dividend', '红利/价值锚'), ('pick', '精选个股'), ('gold', '黄金'), ('hk', '港股通'), ('qdii', 'QDII'), ('theme', '主题')], default='', help_text='留空则按资产类型自动归类；显式设置用于消歧（如区分红利ETF与红利个股）', max_length=20, verbose_name='层内子类别'),
        ),
    ]
